version: "3.9"
services:
  py3:
    build:
      context: ./py3
      dockerfile: Dockerfile
    # メモリのサイズを変える
    shm_size: '16gb'
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/workspace
    expose:
      - "8888"
    #ここの左のポート番号を好きな値に設定 
    ports:
      - "8001:8888"
    # 1.jupyter用 2.ワークスペース用 3.データセット 4.結果の出力先
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./workspace:/workspace
      - ../datasets/conv_feature_points:/workspace/dataset 
      - ../results/conv_feature_points:/workspace/result

    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
